default:
  http_metas:
    content-type: text/html

  metas:
    title:        Admin panel
    #description:  symfony project
    #keywords:     symfony, project
    #language:     en
    robots:       index, follow

  stylesheets:    [/sf/sf_admin/css/main, admin-main]

  javascripts:    []

  has_layout:     on
  layout:         layout
