prod:
  .settings:
    no_script_name:         true
    logging_enabled:        false

dev:
  .settings:
    error_reporting:        <?php echo (E_ALL | E_STRICT)."\n" ?>
    web_debug:              true
    cache:                  false
    no_script_name:         false
    etag:                   false

test:
  .settings:
    error_reporting:        <?php echo (E_ALL | E_STRICT & ~E_NOTICE)."\n" ?>
    cache:                  false
    web_debug:              false
    no_script_name:         false
    etag:                   false

all:
  .actions:
    #error_404_module:       default
    #error_404_action:       error404
    
#    login_module:           administratorAdmin
#    login_action:           login
    
  .settings:
    # Form security secret (CSRF protection)
    csrf_secret:            false
#    standard_helpers: [ Partial, Cache, I18N, Javascript]
    enabled_modules: [ default ]
#    standard_helpers:       [ , sfsCurrency ]
#    enabled_modules:        [ default, countryAdmin, stateAdmin, coreAdmin, coreAdminAdmin, categoryAdmin, brandAdmin, productAdmin, orderAdmin, catalogAdmin, optionTypeAdmin, optionValueAdmin, currencyAdmin, emailTemplateAdmin, deliveryAdmin, administratorAdmin ]
    
#    # i18n
    default_culture:        en        # Default user culture
    i18n:                   true
    # Output escaping settings
    escaping_strategy:      false            # Determines how variables are made available to templates. Accepted values: on, off.
    escaping_method:        ESC_SPECIALCHARS # Function or helper used for escaping. Accepted values: ESC_RAW, ESC_ENTITIES, ESC_JS, ESC_JS_NO_ENTITIES, and ESC_SPECIALCHARS.
    
    # Rich text editor (WYSIWYG)
    rich_text_js_dir:       admin/js/tiny_mce