default:
  http_metas:
    content-type: text/html

  metas:
    title:        Admin panel
    robots:       index, follow

  stylesheets:    ~

  javascripts:    ~

  has_layout:     true
  layout:         layout
