all:
  crypto_key: test
  
  mail:
    address_from: admin@localhost
    address_feedback: nesterukd@gmail.com
    smtp: true
    smtp_host: smtp.inbox.ru
    smtp_port: 25
    smtp_username: nest_d
    smtp_password: irew18t
    
  basket:
      tax:  19.6
  payment:
    paypal_rate: 2.9
    paypal_username: seller_1212764623_biz_api1.inbox.ru
    paypal_password: 1212764627
    paypal_signature: AW5s-AZgM7K7OL1McV49qCXFbPAJAKap7DQ9nPMD5BrcqDEBrHQS7Ox7
    paypal_test_mode: false
    
  recaptcha:
    is_enabled: true
    publickey: 6LeDhgIAAAAAAOUNYtXtoq338WnMtPUL3VetB_QH
    privatekey: 6LeDhgIAAAAAAJu20HFBLPBMsYF4ag0eDBMH47Iu

  store:
    company: sfShop
    owner_name: Dmitry Nesteruk
    address:
      country_id: 227
      state_id: 5
      city: Napa 
      street: 44 Main street
      postcode: '94558'
      phone: 6173335555

test:
  
  recaptcha:
    publickey: 6Lc-SwMAAAAAAJwQAQpZ_fl-cWUF9ACyAwakzgLv
    privatekey: 6Lc-SwMAAAAAAN48a9hzqXLD38zu-cATC1bkGxmv