all:

#  crypto_key: test
#
#  prototype_window:
#    theme: sfshop
#    css: sfshop
#
#    address_from: admin@localhost
#    smtp: true
#    smtp_host: smtp.inbox.ru
#    smtp_port: 25
#    smtp_username: nest_d
#    smtp_password: irew18t
#    
#
#  store:
#    company: sfShop
#    owner_name: Dmitry Nesteruk
#    address:
#      country_id: 227
#      state_id: 5
#      city: Napa
#      street: 44 Main street
#      postcode: '94558'
#      phone: 6173335555
#
#  lucene:
#    index: ProductIndex
