#!/bin/bash

MYSQLDB="devzpc_sfshop"
MYSQLUSER="devzpc_sfUser"
MYSQLPASWD="AAsMM7Yx3:5Q.v4T"



if [ $# -eq 0 ];
then
    ENV="dev"
else
    ENV=$1
fi


function printTime {
    T="$(date +%s)"
    dT=$[$T-$1]
    echo "   ======   time: $dT seconds   ======"
}



#
#   Lock this process
#
if [ -f ./install.lock  ]
then
    T1="$(cat ./install.lock)"
    T2="$(date +%s)"
    dT=$[$T2-$T1]
    echo
    echo "Install script already run ($dT sec)"
    echo "Try to do it later"
    echo
    exit
else
    date
    date '+%s' > ./install.lock
fi



T0="$(date +%s)"
echo '#########################################################################'
echo '#'
echo "# Started install -$ENV- enviroment"
echo '#'
echo '#########################################################################'
echo
echo

mysql -u$MYSQLUSER -p$MYSQLPASWD -e "DROP SCHEMA IF EXISTS $MYSQLDB; CREATE SCHEMA $MYSQLDB DEFAULT CHARACTER SET utf8;"


./clear

rm -f lib/model/om/*.php
rm -f lib/model/map/*.php
rm -f lib/model/*/om/*.php
rm -f lib/model/*/map/*.php
rm -f lib/form/base/*.php
rm -f lib/form/*/base/*.php
rm -f plugins/*/lib/model/om/*.php
rm -f plugins/*/lib/model/map/*.php
rm -f plugins/*/lib/model/*/om/*.php
rm -f plugins/*/lib/model/*/map/*.php
rm -f plugins/*/lib/form/base/*.php
rm -f plugins/*/lib/form/*/base/*.php

rm -f log/*.log

php symfony propel:build-all-load frontend

rm -f data/sql/*
rm -f config/generated-*.xml

printTime $T0

echo
echo
echo '#########################################################################'
echo '#'
echo "# Finished install -$ENV- enviroment"
echo '#'
echo '#########################################################################'

#
#   Unlock this process
#
if [ -f ./install.lock  ]
then
    rm -f ./install.lock
fi

