# default rules
localized_homepage:
  url:   /:sf_culture/
  param: { module: coreAdmin, action: index, sf_culture: en }
  
homepage:
  url:   /
  param: { module: default, action: index, sf_culture: en }

default_symfony:
  url:   /symfony/:action/*
  param: { module: default }

default_index:
  url:   /:sf_culture/:module
  param: { action: index, sf_culture: en }

default:
  url:   /:sf_culture/:module/:action/*
  param: { action: index, sf_culture: en }
