default:
  http_metas:
    content-type: text/html

  metas:
    title:        Admin panel
    #description:  symfony project
    #keywords:     symfony, project
    #language:     en
    robots:       index, follow

  stylesheets:    [ %APP_SFSHOP_ADMIN_CSS_DIR%main ]

  javascripts:    [ ../../js/prototype/prototype, %APP_SFSHOP_ADMIN_JS_DIR%functions ]

  has_layout:     on
  layout:         layout
