all: 
  propel: 
    class:          sfPropelDatabase
    param: 
      encoding:     utf8
      dsn:          mysql://root@localhost/sfshop
  
  session_storage:
    class:          sfPropelDatabase
    param:
      encoding:     utf8
      persistent:   true
      dsn:          mysql://root@localhost/sfshop

