dev:
  propel:
    param:
      classname:  DebugPDO

test:
  propel:
    param:
      classname:  DebugPDO
all: 
  propel: 
    class: sfDoctrineDatabase
    param:
      dsn:        mysql:dbname=devzpc_sfshop;host=localhost
      username:   devzpc_sfUser
      password:   AAsMM7Yx3:5Q.v4T
      encoding:   utf8
      persistent: true
      pooling:    true
      classname:  DoctrinePDO
      
  session_storage:
    class: sfPropelDatabase
    param:
      dsn:        mysql:dbname=devzpc_sfshop;host=localhost
      username:   devzpc_sfUser
      password:   AAsMM7Yx3:5Q.v4T
      encoding:   utf8
      persistent: true
      pooling:    true
      classname:  DoctrinePDO
