all:
  mailer:
    class: sfMailer
    param:
      logging:           %SF_LOGGING_ENABLED%
      charset:           %SF_CHARSET%
      delivery_strategy: none
#      spool_class:       Swift_DoctrineSpool
#      spool_arguments:   [ MailMessage, message ]
#      transport:
#        class: Swift_SmtpTransport
#        param:
#          host:       localhost
#          port:       25
#          encryption: ~
#          username:   my user
#          password:   my pass