default:
  http_metas:
    content-type: text/html

  metas:
    #title:        symfony project
    #description:  symfony project
    #keywords:     symfony, project
    #language:     en
    robots:       index, follow

  stylesheets:    [%APP_SFSHOP_INSTALL_CSS_DIR%main]

  javascripts:    []

  has_layout:     on
  layout:         layout
