all:
  crypto_key: test
  
  mail:
    address_from: admin@localhost
    address_feedback: nesterukd@gmail.com
    smtp: true
    smtp_host: smtp.inbox.ru
    smtp_port: 25
    smtp_username: nest_d
    smtp_password: irew18t
    
  basket:
      tax:  19.6
  payment:
    paypal_rate: 2.9
    paypal_username: seller_1212764623_biz_api1.inbox.ru
    paypal_password: 1212764627
    paypal_signature: AW5s-AZgM7K7OL1McV49qCXFbPAJAKap7DQ9nPMD5BrcqDEBrHQS7Ox7
    paypal_test_mode: false
    
  recaptcha:
    publickey: 6LcXjwIAAAAAADl7uoxfPIB6za8FIrGJQGupED1I
    privatekey: 6LcXjwIAAAAAAB2Mi1QLJ684fQJYEBnn-OKI3aPw

  store:
    company: sfShop
    owner_name: Dmitry Nesteruk

dev:
  payment:
    paypal_test_mode: true
  
  recaptcha:
    publickey: 6LeDhgIAAAAAAOUNYtXtoq338WnMtPUL3VetB_QH
    privatekey: 6LeDhgIAAAAAAJu20HFBLPBMsYF4ag0eDBMH47Iu