default:
  http_metas:
    content-type: text/html

  metas:
    title:        sfShop - online shop
    description:  Open Source online shop e-commerce solution
    keywords:     symfony, sfShop, online, e-commerce, open source
    language:     en
    robots:       index, follow

  stylesheets:    [main]

  javascripts:    []

  has_layout:     on
  layout:         layout
