dev:
  propel:
    param:
      classname:  DebugPDO

test:
  propel:
    param:
      classname:  DebugPDO
all: 
  propel: 
    class: sfPropelDatabase
    param:
      dsn:        mysql:dbname=equipmoto2;host=localhost
      username:   root
      password:   timpwdfpc
      encoding:   utf8
      persistent: true
      pooling:    true
      classname:  PropelPDO
      
  session_storage:
    class: sfPropelDatabase
    param:
      dsn:        mysql:dbname=equipmoto2;host=localhost
      username:   root
      password:   timpwdfpc
      encoding:   utf8
      persistent: true
      pooling:    true
      classname:  PropelPDO
