all: 
  propel: 
    class:          sfPropelDatabase
    param: 
      dsn:          mysql://devzpc_sfUser:AAsMM7Yx3:5Q.v4T@localhost/devzpc_sfshop
  
  session_storage:
    class:          sfPropelDatabase
    param:
      persistent:   true
      dsn:          mysql://devzpc_sfUser:AAsMM7Yx3:5Q.v4T@localhost/devzpc_sfshop

